### ISSUE TITLE
Only returns logs one error line.

### ISSUE THREAD

**Issue by GCollado** [GCollado/IS211_Assignment2#3]
When running the error.log, it only displays: 'Error processing line #1 for ID #id."

**Comment by GCollado** [comment]
When searching for ID, for example, I get the Traceback error:
"""Traceback (most recent call last):
  File "Assignment2.py", line 108, in <module>
    main()
  File "Assignment2.py", line 104, in main
    displayPerson(choice, personData)
  File "Assignment2.py", line 81, in displayPerson
    for key,values in personData:
ValueError: not enough values to unpack (expected 2, got 1)"""
